config/routes.rb
Rails.application.routes.draw do
 root "dashboard#index"
 resources :sessions, only: [:new, :create]
  resource :registrations
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ensure_authenticated_user

  def ensure_authenticated_user
    redirect_to new_session_path unless current_user
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  # skip_before_filter :ensure_authenticated_user
def show
  @user = User.new
end

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      firstname: params[:user][:firstname],
      lastname: params[:user][:lastname],
      email: params[:user][:email],
      password: params[:user][:password]
    )

    if @user.save
      flash[:notice] = "Thank you for registering!"
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :ensure_authenticated_user

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])

    if @user && user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Thank you"
      redirect_to root_path
    else
      @user = User.new(email: params[:user][:email])
      @user.errors[:base] << "Email/ password are invalid"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>LadyCoders</title>
  <link href="css/bootstrap.min.css" rel="stylesheets">
  <link href="css/font-awesome.min.css" rel="stylesheets">
  <link href="css/animate.min.css" rel="stylesheets">
  <link href="css/lightbox.css" rel="stylesheets">
  <link href="css/main.css" rel="stylesheets">
  <link href="css/responsive.css" rel="stylesheets">
</head>
<!--/head-->
<%= link_to "Join", new_registrations_path, :class => "green" %>
<body>
<header id="header">
  <div class="container">
    <div class="row">
      <div class="column">
        <div class="social-icons pull-right">
          <ul class="nav nav-pills">
            <li><a href=""><i class="fa fa-facebook"></i></a></li>
            <li><a href=""><i class="fa fa-twitter"></i></a></li>
            <li><a href=""><i class="fa fa-google-plus"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar-inverse" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    </div>
  </div>
  <!--/#home-slider-->

  <section id="services">
    <div class="container">
      <div class="row">
        <div class="col-sm-4 text-center padding wow fadeIn" data-wow-duration="1000ms" data-wow-delay="300ms">
          <div class="single-service">
            <div class="wow scaleIn" data-wow-duration="500ms" data-wow-delay="300ms">
              <img src="images/home/icon1.png" alt="">
            </div>
            <h2>What women want</h2>

            <p>We want pizza!</p>
          </div>
        </div>
        <div class="col-sm-4 text-center padding wow fadeIn" data-wow-duration="1000ms" data-wow-delay="600ms">
          <div class="single-service">
            <div class="wow scaleIn" data-wow-duration="500ms" data-wow-delay="600ms">
              <img src="images/home/icon2.png" alt="">
            </div>
            <h2>Why Women in Tech!</h2>

            <p>Because cheeseburgers rule!</p>
          </div>
        </div>
        <div class="col-sm-4 text-center padding wow fadeIn" data-wow-duration="1000ms" data-wow-delay="900ms">
          <div class="single-service">
            <div class="wow scaleIn" data-wow-duration="500ms" data-wow-delay="900ms">
              <img src="images/home/icon3.png" alt="">
            </div>
            <h2>More Info</h2>

            <p>More food!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

</header>
<div class="col-md-3 col-sm-6">
  <div class="contact-info bottom">
    <h2>Contacts</h2>
    <address>
      E-mail: <a href="mailto:kelly.pederson@gmail.com">kelly.pederson@gmail.com</a> <br>
      Phone: +1 (925) 963 1921 <br>
    </address>

    <h2>Address</h2>
    <address>
      gSchool <br>
      1062 Delaware St <br>
      Denver, CO 80204 <br>
      United States of America <br>
    </address>
  </div>
</div>
<div class="col-md-4 col-sm-12"> // col-md-4 col-sm-12
  <div class="contact-form">
    <h2>Send a message</h2>
    <form id="main-contact-form" name="contact-form" method="post" action="sendemail.php">
      <div class="form-group">
        <input type="text" name="name" class="form-control" required="required" placeholder="Name">
      </div>
      <div class="form-group">
        <input type="email" name="email" class="form-control" required="required" placeholder="Email Id">
      </div>
      <div class="form-group">
        <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your text here"></textarea>
      </div>
      <div class="form-group">
        <input type="submit" name="submit" class="btn btn-submit" value="Submit">
      </div>
    </form>
  </div>
</div>
<div class="col-sm-12">
  <div class="copyright-text text-center">
    <p>&copy; Kelly Pederson 2014. All Rights Reserved.</p>
  </div>
</div>
</div>
</div>
</footer>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_include_tag 'application' %>


<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/lightbox.min.js"></script>
<script type="text/javascript" src="js/wow.min.js"></script>
<script type="text/javascript" src="js/main.js"></script>
</body>
</html>